# Generated by Django 3.1.2 on 2020-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='projectTitle',
            field=models.CharField(default='', max_length=50, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='fileName',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='STL File'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobDetails',
            field=models.TextField(verbose_name='Job Details'),
        ),
    ]
