# Generated by Django 3.1.2 on 2021-06-18 05:07

import JobTracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTracker', '0002_auto_20201109_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['dateRequested'], 'verbose_name': 'Job List'},
        ),
        migrations.AlterField(
            model_name='job',
            name='fileName',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[JobTracker.validators.validateFileExtension], verbose_name='STL File'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobDetails',
            field=models.TextField(blank=True, default='', verbose_name='Job Details'),
        ),
    ]
