# Generated by Django 3.1.2 on 2021-06-26 18:25

import RouteTracker.validators
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastAccessDate', models.DateTimeField(auto_now=True)),
                ('isAdminUser', models.BooleanField(default=False)),
                ('studentId', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'ordering': ['-username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeId', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('initialSOC', models.IntegerField()),
                ('batteryCapacity', models.IntegerField()),
                ('routeTitle', models.CharField(default='', max_length=50, verbose_name='Route Title')),
                ('batteryRating', models.IntegerField()),
                ('chargingTime', models.IntegerField()),
                ('fileName', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[RouteTracker.validators.validateFileExtension], verbose_name='timetable')),
                ('departure', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('transit', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('arrival', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('stay', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('calcSOC', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('minDeparturePow', models.IntegerField()),
                ('maxDeparturePow', models.IntegerField()),
                ('transitPow', models.IntegerField()),
                ('minArrivalPow', models.IntegerField()),
                ('maxArrivalPow', models.IntegerField()),
                ('stayingPow', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Route List',
                'db_table': 'Route',
                'ordering': ['dateAdded'],
            },
        ),
    ]
