# Generated by Django 3.1.2 on 2021-06-29 13:44

import RouteTracker.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='arrival',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None, verbose_name='Arrival'),
        ),
        migrations.AlterField(
            model_name='route',
            name='batteryCapacity',
            field=models.IntegerField(verbose_name='Battery Capacity (Kwh)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='batteryRating',
            field=models.IntegerField(verbose_name='Battery Rating (VDC)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='chargingTime',
            field=models.IntegerField(verbose_name='Charging Time (m)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None, verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='route',
            name='fileName',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[RouteTracker.validators.validateFileExtension], verbose_name='Vessel Timetable File'),
        ),
        migrations.AlterField(
            model_name='route',
            name='initialSOC',
            field=models.IntegerField(verbose_name='Initial SOC (%)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='maxArrivalPow',
            field=models.IntegerField(verbose_name='Max Arrival Power Req'),
        ),
        migrations.AlterField(
            model_name='route',
            name='maxDeparturePow',
            field=models.IntegerField(verbose_name='Max Departure Power Req'),
        ),
        migrations.AlterField(
            model_name='route',
            name='minArrivalPow',
            field=models.IntegerField(verbose_name='Min Arrival Power Req'),
        ),
        migrations.AlterField(
            model_name='route',
            name='minDeparturePow',
            field=models.IntegerField(verbose_name='Min Departure Power Req'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None, verbose_name='Stay'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stayingPow',
            field=models.IntegerField(verbose_name='Stay Power Req'),
        ),
        migrations.AlterField(
            model_name='route',
            name='transit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None, verbose_name='Transit'),
        ),
        migrations.AlterField(
            model_name='route',
            name='transitPow',
            field=models.IntegerField(verbose_name='Transit Power Req'),
        ),
    ]
