# Generated by Django 3.1.2 on 2021-06-29 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteTracker', '0002_auto_20210629_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='calcSOC',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
